name: openapi validate
on: push
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3

      - name: install swagger cli
        run: npm install -g @apidevtools/swagger-cli
      
      - name: validate
        run: swagger-cli validate ./openapi/spec3.yml

        
